services:
  - type: web
    name: chaicast
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
    disk:
      name: chaicast-data
      mountPath: /opt/render/project/src/output
      sizeGB: 1
